TEST := server-tcp
TEST += client-tcp


CC = gcc

CFLAGS += -g -Wall -Wextra -Wpedantic \
          -Wformat=2 -Wno-unused-parameter -Wshadow \
          -Wwrite-strings -Wstrict-prototypes -Wold-style-definition \
          -Wredundant-decls -Wnested-externs -Wmissing-include-dirs 
CFLAGS += -Wnull-dereference -Wjump-misses-init -Wlogical-op

all: $(TEST)


$(TEST): %: %.o 
	$(CC) $(CFLAGS) $+ -o '$@'